---
- hosts: all
  user: root
  tasks: 
  - name: Install NGINX package
    package: 
      name: nginx
      state: present
    notify: Package Installed
  handlers:
    - name: Package Installed
      debug: 
        msg: NGINX installed successfully
