---
- hosts: all
  user: root
  tasks: 
  - name: Remove NGINX package
    package: 
      name: nginx
      state: absent
    notify: NGINX removed 
  handlers:
    - name: NGINX removed
      debug: 
        msg: NGINX removed successfully
